Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.vm.box = "ubuntu/focal64"
  config.vm.define "homelab", primary: true do |h|
    h.vm.network "private_network", ip: "192.168.100.100"
  config.vm.provision "shell" do |s|
  ssh_pub_key = File.readlines("/home/tom/.ssh/id_rsa.pub").first.strip
  s.inline = <<-SHELL
  echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
  echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
  SHELL
  end
  end
end