---

- name: Bring the vagrant machine up
  command: vagrant up
  args:
    chdir: ../vagrant

- name: Remove the key of any previous vagrant machines with the same ip from the local known_hosts file
  known_hosts:
    name: "{{ groups[homelab] }}"
    state: absent

- name: Pause for 2 minutes to let ssh come up
  pause:
    minutes: 2
